name: firstapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - resources/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: resources/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: resources/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: resources/fonts/Montserrat-Regular.ttf